# Generated by Django 3.2.5 on 2022-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordListDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='Predicted Person')),
                ('record_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d', verbose_name='Unknown Person Image')),
            ],
        ),
    ]
