# Generated by Django 3.2.5 on 2022-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objrecog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordlistdb',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Person Image'),
        ),
    ]
